version: "3.11.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:sage7896@db:5432/nivada

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sage7896
      POSTGRES_PASSWORD: sage@7896
      POSTGRES_DB: nivada
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
